export enum IncidentCategory {
  SEVERE_STORM = 'SEVERE_STORM',
  FLOOD = 'FLOOD',
  LANDSLIDE = 'LANDSLIDE',
  FIRE = 'FIRE',
  INTENSE_WIND = 'INTENSE_WIND',
  HIGH_TEMPERATURES = 'HIGH_TEMPERATURES',
  OTHERS = 'OTHERS',
}
